mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
    views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
    views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/cats/urls.py
from django.urls import path

from . import views
# from django.views.generic import TemplateView

app_name = "cats"

urlpatterns = [
    # path("", views.IndexView.as_view(), name="index"),
        path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/mysite/backup/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Add
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('ads/', include('ads.urls')),
    path('polls/', include('polls.urls')),
    # path('cats/', include('cats.urls')),
    # path('views/', include('views.urls')),
    # path('route/', include('route.urls', namespace='nsroute')),
    # path('tmpl/', include('tmpl.urls')),
    # path('gview/', include('gview.urls')),
    # path('session/', include('session.urls')),
    # path('authz/', include('authz.urls')),
    # path('getpost/', include('getpost.urls')),
    # path('form/', include('form.urls')),
    # path('crispy/', include('crispy.urls')),
    # path('myarts/', include('myarts.urls')),
    # path('menu/', include('menu.urls')),
    # path('forums/', include('forums.urls')),
    # path('pics/', include('pics.urls')),
    # path('favs/', include('favs.urls')),
    # path('favsql/', include('favsql.urls')),
    # path('rest/', include('rest.urls')),
    # path('autos/', include('autos.urls')),
    # path('usermodel/', include('usermodel.urls')),
    # path('fetch/', include('fetch.urls')),
    # path('chat/', include('chat.urls')),
    # path('util/', include('util.urls')),
    # path('well/', include('well.urls')),
    # path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

mysite/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from cats.models import Cat,Breed
from django.urls import reverse_lazy
# Create your views here.
# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Breed.objects.count()
        al = Cat.objects.all()

        ctx = {'breed_count': mc, 'cat_list': al}
        return render(request, 'cats/cat_list.html', ctx)


class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Breed.objects.all()
        ctx = {'breed_list': ml}
        return render(request, 'cats/breed_list.html', ctx)


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

    # We use reverse_lazy() because we are in "contructor attribute" code
# that is run before urls.py is completely loaded
class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')
    # return redirect(self.success_url)

# and no form by extending UpdateView
class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')


class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breed in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
  <p>
    <a href="{% url 'cats:all' %}">Back to cats</a>
  </p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cat List</h1>
  {% if cat_list %}
  <ul>
    {% for cat in cat_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
          <!--{{ cat. }} ({{ auto.mileage }} miles)-->
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the library.</p>
  {% endif %}
  <p>
    {% if breed_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a breed before you add an cat.
    {% endif %}
  </p>
   <p>
    <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}